# Generated by Django 2.2.7 on 2019-11-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191104_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
